### ISSUE TITLE
Convert Variables

### ISSUE THREAD

**Issue by mindaptiv** [mindaptiv/Foster#1]
-Convert string/wstring to utf8
-Convert various integer types to appropriate for export

**Comment by Scrubsauce** [comment]
WinRT returns user account image in this format, brainstorm ways to convert for exporting?
(note: Filetype of current returned image is returning as .png)
https://msdn.microsoft.com/en-us/library/windows.storage.istoragefile.aspx

**Comment by Simulacrum0** [comment]
PNG is fine.  We already have several readers for PNG, but we'll want to support their 'native' reader....for now we can report a filename, ( or just dimensions X & Y if no name is avail ?) and pause for now as i need to put a stub in to show images.  That'd be close enough to unify all Cylons and step ahead-

**Comment by Scrubsauce** [comment]
Cross post w/ #6  for Microsoft DeviceInformation classes

**Comment by Scrubsauce** [comment]
WideChar to Multibyte for wstrings:
http://stackoverflow.com/questions/215963/how-do-you-properly-use-widechartomultibyte

**Comment by Scrubsauce** [comment]
Based on decisions from #6, will convert MS DeviceInformation objects into deviceStructs.

**Comment by Scrubsauce** [comment]
Converted hertz from uint64 to float32 w/ 3adc6cc3b529e332daea5d922d007cffbc977dbb

**Comment by Scrubsauce** [comment]
Convert processorCount from unsigned long to UINT64 w/ dc694b96b444f8f0465323d98571b2ffa88387c5

**Comment by Scrubsauce** [comment]
Convert memoryBytes from uint64 to UINT64 w/ 86bc4ae7ff32c7ec6bd94947eb1e5fa0e7e22381

**Comment by Scrubsauce** [comment]
Convert pictureType from std::wstring to utf8 std::string w/ 4933405208ed516366e2b600230d82c2f1f06fcc

**Comment by Scrubsauce** [comment]
Convert timeZoneName from std::wstring to utf8 std::string w/ 269786dc30ffdc316a9ef540f47263d76c20e3a0

**Comment by Scrubsauce** [comment]
Convert username from std::wstring to utf8 std::string w/ 14b98493139e97dd35507aa51a125a372e2a9ab5

**Comment by Scrubsauce** [comment]
Convert deviceName from std::wstring to utf8 std::string w/ e6d67ac15f1f6f4dfe552664b54e0d205a94d20b

**Comment by Scrubsauce** [comment]
Convert deviceStruct name member variable from std::wstring to utf8 std::string w/ bdbec96ceb25ab7b52f1e86f6a7523ab23614e6e

**Comment by Scrubsauce** [comment]
Convert deviceStruct id member variable from std::wstring to utf8 std::string w/ 5ab71e574d7bad3c7472df6a89d861e6cda3a38f

**Comment by Scrubsauce** [comment]
Preliminary mappings scheme to be used from @Simulacrum0  in #55:

bool -> uint32 -> Yes_t ( can be stored as byte, short, int, long long pending function need or storage need)

float32 -> F32 -> F_t
double -> F64 -> Df_t
(Note: you should not need byte-float, short float in your work)

UBYTE -> unsigned byte -> uint8 -> Bu_t
WORD -> unsigned short -> uint16 - > Su_t
DWORD-> unsigned int -> uint32 -> U_t
unsigned int -> uint32 -> U_t
long unsigned int -> uint64 -> Du_t

BYTE -> signed byte -> int8 -> Bi_t
SHORT -> short integer -> int16 -> Si_t
long -> signed integer -> int32 -> I_t
long long -> signed long long -> int64 -> Di_t

void\* -> generally a 64bit pointer for all platforms ( 32 on earlier Android/iOS ). Void_tp

std::list will have to be done manually later

**Comment by Scrubsauce** [comment]
stdint.h:
http://www.cplusplus.com/reference/cstdint/

**Comment by Scrubsauce** [comment]
Convert structs ints (most) with these commits:
6fd5d71e0757bfec5747f9d3c5892255b43c8746
5dd6a830cdbc3da16b3750f7e3aec55c7cf60917
ee97fdc329b66db5a43c0b967a050ecee3d8143b
5b78181cb778ac0935ec4eb4fb4ec263bd89c80e

**Comment by Scrubsauce** [comment]
Converting void*:
http://stackoverflow.com/questions/1640423/error-cast-from-void-to-int-loses-precision

**Comment by Scrubsauce** [comment]
Refactored IStorageFile^ for account picture to uintptr_t w/ #52

**Comment by Scrubsauce** [comment]
uintptr_t changes size-
http://zone.ni.com/reference/en-XX/help/370051T-01/cvi/programmerref/porting32bitto64bit/

**Comment by Scrubsauce** [comment]
Convert void*'s to uintptr_t's: 4c18350087aa38fde210441a2d11e75827d22e7a

**Comment by Scrubsauce** [comment]
Convert float32's to float's w/ 95eea701e6a65de3074a8cc7595766f9d373744a
