### ISSUE TITLE
Add 6 basic inputs

### ISSUE THREAD

**Issue by mindaptiv** [mindaptiv/Foster#2]
Up, Down, Left, Right, Enter, Esc, or equivalent

Add code to testing project (NOT FOR repo push!)

**Comment by Scrubsauce** [comment]
DirectInput vs. Windows Message Loop:
http://stackoverflow.com/questions/2165230/should-i-use-directinput-or-windows-message-loop/2166341#2166341

**Comment by Scrubsauce** [comment]
Tutorial: add look-move controls:
https://msdn.microsoft.com/en-us/library/windows/apps/hh452773.aspx

-Possibly repurpose response of keybindings to update labels for testing/debugging
