### ISSUE TITLE
Status update 3/3

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#38]

**Comment by Scrubsauce** [comment]
Test:
`if(device.type == 8)
{
   displayStruct = cylon.displayList[device.displayIndex];
   //Do something with display metadata (dpi, scale, etc.)
}
`

**Comment by Simulacrum0** [comment]
1) Sharing WhiteBoard has been good/useful+
2) Bummed to hear this process continues to vex...wish there was time to intercede/help...sorry on delays.  Encouraging that you've found a solution though.  Well done in that regard+
3) Good choice to leave as comments for now
4) Good+
