### ISSUE TITLE
Pointer Storage

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#57]
Trying to store pointer addresses as numerical values (uint64_t).  However, I notice that the addresses the debugger is giving me are all 32 bits, but maybe I'm targeting 32-bit without realizing and its the default for Visual Studio for this type of project?  WinRT apps don't have the ability to check if they're 32 or 64 bit so I can't do like an IF 32BIT, ELIF 64BIT deal like I've seen in some of Apple's examples.  (These may be dumb questions, but this is the first time I've had to code with the 32 vs. 64 paradigm concern)

Q: Should I be pre-pending all 0's or all F's when saving a 32-bit pointer?  I want to say 0's.
My concern is over these two approaches I've been testing:
Option a. void\* -> uint64_t   this prepends all f's, but if the pointer is originally 32-bit I want to make sure this won't cause issues
![screen shot 2015-03-11 at 12 40 47 pm](https://cloud.githubusercontent.com/assets/2531841/6604112/eb2d9184-c7eb-11e4-833d-c3fc3f570e93.png)

Option b. void\* -> uint32_t -> uint64_t this prepends all 0's, but if the pointer is originally 64-bit we may lose precision
![screen shot 2015-03-11 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/2531841/6604107/e5009298-c7eb-11e4-95aa-f7da167b77b3.png)

What I've done with commit  4cf5eee7d9fc3792b170c5c13e9e209c0542b0a9:
Since I suspect neither of the previous two options are appropriate in all cases (please let me know otherwise), I've added some simple if-logic to check:
Step 1: Convert from void\* to uintptr_t (this is what all the documentation I read today suggested, and it seems like it defaults to the size of the pointer)
Step 2: Check if the uintptr_t  > 0xffffffff, if yes use option a, otherwise use option b.  

This way 64-bit pointers don't lose precision, and 32-bit pointers don't get a bunch of 1's prepended to them.  Up to change this however you'd see fit, maybe I'm worrying for nothing, I just want it to be correct.  Since it looks like my test directx project is currently targeting 32-bit, I'll wait for your input on this, then test a 64-bit flavor to see if everything works.

I'd need to test it but I think technically I COULD just use uintptr_t for pointer values instead of uint64_t, since stdint.h defines uintptr_t just like the other types we're using?

**Comment by Simulacrum0** [comment]
I must've failed to explain this morning that we didn't want to store a "void *" directly as it'll be 32 or 64 ( or really on 40 or 48 relevant bits like on iOS-64 or Lollipop ).  

We only want to store uint64_t.
We will never 'read' indirectly from the min/max Memory, just use it for comparisons with other uint64_t values...so that just does it.

'a' ftw

**Comment by Scrubsauce** [comment]
In hindsight (now that I've dealt with it on my own) that makes sense and I see why haha.

So going with option a, and you don't really mind if we get all those f's at the beginning of a pointer if its 32-bit?

**Comment by Scrubsauce** [comment]
Also from #58, since uintptr_t is acceptable for the picture location value, can we use uintptr_t for these two values as well?  (would avoid the prepending drama)

**Comment by Scrubsauce** [comment]
Ah nvm, false alarm, read the response in #58 wrong.  Carry on!
