### ISSUE TITLE
Grab Available Device Information

### ISSUE THREAD

**Issue by mindaptiv** [mindaptiv/Foster#6]
Retrieve relevant data available for:
-Storage Devices
     --Total size
     --Free size
-USB Devices
     --Controllers, etc.
-Screens
     --Make
     --Model
     --Refresh rate
     --Resolution
     --Color profile
-Speakers
-Cameras (non depth-sensing)
-Microphones

Device Properties Expected:
1. Unique ID
2. Name
3. Enabled?
4. Default?
5. Icon
6. Physical Device Location

**Comment by Scrubsauce** [comment]
Option 1: FindAllAsync() code.msdn.microsoft.com/windowsapps/Account-picture-name-sample-912baff1
-Attempted this method, but it returns all installed devices, regardless of their availability to the computer at runtime.  
-Significantly slows down response rates of build cylonStruct methods. (~4 FPS)
-Ran tests with plugging in new phones and removing them.  Device count would rise for each new device attached/installed, but would never decrease.  Basically returns the list you might see in the Device Manager or something very similar

**Comment by Scrubsauce** [comment]
Option 2: FindAllAsync(Windows::Devices::Enumeration::DeviceClass): https://msdn.microsoft.com/en-us/library/windows/apps/br225435.aspx?f=255&MSPPError=-2147217396

-Filters devices returned by specific type, available enumerations are: all devices, audio capture, audio rendering, portable storage, video capture

-Filters exclusive to Windows 8.1 are image scanner, and location aware devices

-When testing with USB storage devices, FPS dropped to about 7-9, some devices took longer to be recognized (possibly tied to length of their usb cord), devices that were disconnected disappeared immediately from the returned count though, and no internal storage was ever returned

-When testing for audio rendering devices, maintained 60 FPS, returned a count of 3 devices (internal tower speaker, digital out and analog out ports from tower)

-When testing for audio recording devices, maintained 60 FPS and returned a count of 2 for analog out and digital out on the tower, tried attaching an additional microphone with no drivers installed and the count did not update

-When testing for image scanners, maintained 60 FPS and returned a count of 0, despite having three network all-in-ones available.  This method may only work for scanners attached via USB, or I could be misinterpreting the meaning of image scanner.

-When testing for location aware devices, maintained 59-60 FPS and returned a count of 1.  MS has used "location aware" to refer to a printing service before, so this may be the all in one, or it could be something else internal to the tower (like what Apple uses for iCloud tracking of stolen computers?  not too familiar with that service but I've seen it when setting up new machines here).  I scrolled through the device manager and didn't see anything at first pass that was dedicated to location-awareness-based services.  Putting a break point in and inspecting the name property of this device, I'm receiving the name "MIND-PRO-01" (the name of the computer), for other tests I received more specific names like "High Definition Audio Device"

-Filtering on All returns the same results as option 1

-When making calls for all of the above filters at run time (excluding "All"), FPS holds at ~5

-There is currently no enumeration value for controller or screens (the two missing device types from the requirements list above)

**Comment by Scrubsauce** [comment]
Both options return a DeviceInformationCollection object: 
https://msdn.microsoft.com/library/windows/apps/br225395

Which is like a vector of DeviceInformation objects:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.enumeration.deviceinformation

**Comment by Scrubsauce** [comment]
Current properties I'm retrieving for a given device (default choices):
1. Name
2. Device Instance ID
3. Icon
4. Interface Enabled?
5. Is Default?
6. Physical Device Location

Other properties we can request (depending on the type of device):
https://msdn.microsoft.com/en-us/library/windows/apps/hh464997#ListOfCanonicalProperties
1. Children Device Instance ID's
2. Compatible ID's for Device
3. Device Container ID
4. Device Capabilities Bitmask
5. Device Characteristics Bitmask
6. Device has Problem?
7. Device Hardware ID's
8. Is Device Devnode in the Computer's Container?
9. Device Discovery Methods
10. Device is Connected?
11. Device is Paired?
12. Device Container is Local Machine? (would probably be true for the location aware test above)
13. Device Metadata Path
14. Launch Device Stage from Win Explorer?
15. Device Description
16. Device is Shared?
17. Device is Connected to Network?
18. Device Category
19. Device Category Group
20. Device Manufacturer 
21. Model Number
22. Model Name

NOTE: if we want additional properties for a device, this means we will have to refactor how we currently retrieve, while this process appears relatively easy to implement for Storage, Image Scanning, and Service Devices, I have not yet found ways to add properties to the other filter types, this would in implementation be more of an option 3, because we would be using a different FindAllAsync method that uses AQS strings to filter.  However, not every enumerated type in DeviceClass has its own getDeviceSelector method to return its AQS string so this would still be limited in scope to what we could filter by.  

An option 4, would be if we FOUND a device we wanted to know more about in the Collection, I can then ping additional properties for it using CreateFromIdAsync(), as all that method requires is the device ID.
https://msdn.microsoft.com/en-us/library/windows/apps/br225426.aspx
I suppose it would be possible to just iterate over every found device (whether we're talking about a list of <~10 connected devices or all 200+ installed devices) and request additional properties that you want for every device we find.  My only concern is that for every additional asynchronous call we make, the response latency continues to rise.  This would probably be the least headache inducing route in my opinion (as option 3 based on documentation does not appear to be useable for every possible device type), but I'm wary of the lag it could create.

**Comment by Scrubsauce** [comment]
After determining which option and which properties we want:
How do we want to store all this information?

Cross post to #1 

Conversion Method 1- Could simply store the DeviceInformationCollection's for each type and send them out in the cylonStruct (currently doing this for debugging purposes).  However, if we want cylonStruct to be a platform agnostic structure this won't work because DeviceInformationCollection is a Windows-based class.  Option 1 would assume that cylonStruct is no longer necessarily platform independent, and that there might be variations for differing platforms.

Conversion Method 2- Could create a new struct, and store an array of this newStruct inside of cylonStruct for holding all the various devices we detect.  This may still cause issues down the line if we want cylonStruct to be a multiplatform struct if for example Windows uses a bitmask for a specific property, and Android uses a different enumeration scheme.  We would have to create an additional layer of translation to standardize everything, which we are currently doing in a small scope for processor specs, etc.

Conversion Method 3- Have platform specific properties for devices.  When returning from a given operating system, say iOS, all the Windows, Android, etc. properties would be null, but iOS would have its expected data filled in.  This seems the least feasible because we would still need some translation in place because we wouldn't be able to store information in platform specific classes like DeviceInformationCollection, etc.

Conversion Method 4s- ??? Super magical suggestion that I totally haven't thought of in the last 20 minutes ???

**Comment by Scrubsauce** [comment]
From the 2/20 call w/ @Simulacrum0 
Retrieval- Stick with Option 2, with a chance to revisit Option 4 later.  Still need to find additional ways to retrieve controllers and monitors.

Conversion- Employ Method 2 across all projects, and Method 3 as needed for important, platform-specific data members.

**Comment by Scrubsauce** [comment]
Display Information Class:
https://msdn.microsoft.com/en-us/vstudio/windows.graphics.display.displayinformation

**Comment by Scrubsauce** [comment]
Detecting Resolution in app:
http://programmerpayback.com/2013/08/31/detecting-screen-resolution-in-windows-8-and-windows-phone-apps/

**Comment by Scrubsauce** [comment]
Win32 options (Tyrol?):
http://stackoverflow.com/questions/4631292/how-detect-current-screen-resolution

**Comment by Scrubsauce** [comment]
Correct Display Information Class:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.display.displayinformation

**Comment by Scrubsauce** [comment]
Polymorphic Structures:
http://stackoverflow.com/questions/18422002/best-approach-for-struct-polymorphism-in-c

**Comment by Scrubsauce** [comment]
DisplayInformation only retrieves color profile, dpi, etc. for primary display (assuming built with tablets and phones in mind).

**Comment by Simulacrum0** [comment]
Probably should discuss this Josh---Seems like there might be some confusion on the Cylon structs?  Perhaps a _brief_ check in call tmrw @ 9MST ( or lemme know the 'ideal time' for you so i can package up notes/etc.

Progress looking good though sir!

**Comment by Scrubsauce** [comment]
Get Color Profile:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.display.displayinformation.getcolorprofileasync

**Comment by Scrubsauce** [comment]
Quick typedef reference:
http://stackoverflow.com/questions/27755443/error-this-declaration-has-no-storage-class-or-type-specifier-me-making-a-sim

**Comment by Scrubsauce** [comment]
Problem: Trying to allocate a `new displayStruct` pointer, then replicate process for deviceStruct.

Changes I've made to local branch: 
a. in cylonStruct: Added a new member variable for testing `displayStruct* monitor`

b. in foster.cpp: Changed `buildDisplay()` function name to `displayStruct()` to match struct name.

c. In buildTory(): tried `new` allocation to keep pointer from turning to garbage after buidTory() returns.  So added test line: `tory.monitor = new displayStruct(testDevice, testDisplayInfo);`  The constructor function following the new keyword was giving the error: `"expected a type specifier"`

d. In response to c, refactored displayStruct from `struct displayStruct{...};` to `typedef struct{...}displayStruct;`
However, now all earlier mentions of displayStruct give the error: `"incomplete type is not allowed"`, as an example:
`struct displayStruct testDisplay = displayStruct(testDevice, testDisplayInfo);`
gives the same error.

**Comment by Scrubsauce** [comment]
DisplayStruct constructor:
`//builds a displayStruct from a given deviceStruct
struct DisplayStruct DisplayStruct(struct deviceStruct superDevice, Windows::Graphics::Display::DisplayInformation^ displayInformation)
{
	//Variable Declaration
	struct DisplayStruct displayDevice;

	//Set parent struct
	displayDevice.superDevice = superDevice;

	//Set member variables
	//preferred app orientation
	if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::None)
	{
		displayDevice.rotationPreference = 0;
	}
	else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::Landscape)
	{
		displayDevice.rotationPreference = 1;
	}
	else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::Portrait)
	{
		displayDevice.rotationPreference = 2;
	}
	else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
	{
		displayDevice.rotationPreference = 4;
	}
	else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
	{
		displayDevice.rotationPreference = 8;
	}
	else
	{
		//error case
		displayDevice.rotationPreference = 0;
	}//END if orientation

	//current monitor orientation
	if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::None)
	{
		displayDevice.currentRotation = 0;
	}
	else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::Landscape)
	{
		displayDevice.currentRotation = 1;
	}
	else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::Portrait)
	{
		displayDevice.currentRotation = 2;
	}
	else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
	{
		displayDevice.currentRotation = 4;
	}
	else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
	{
		displayDevice.currentRotation = 8;
	}
	else
	{
		//error case
		displayDevice.currentRotation = 0;
	}//END current monitor orientation

	//native monitor orientation
	if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::None)
	{
		displayDevice.nativeRotation = 0;
	}
	else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::Landscape)
	{
		displayDevice.nativeRotation = 1;
	}
	else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::Portrait)
	{
		displayDevice.nativeRotation = 2;
	}
	else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
	{
		displayDevice.nativeRotation = 4;
	}
	else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
	{
		displayDevice.nativeRotation = 8;
	}
	else
	{
		//error case
		displayDevice.nativeRotation = 0;
	}//END if native monitor orientation

	//DPI
	displayDevice.logicalDPI	= displayInformation->LogicalDpi;
	displayDevice.rawDPIX		= displayInformation->RawDpiX;
	displayDevice.rawDPIY		= displayInformation->RawDpiY;

	//Stereoscopic 3D
	displayDevice.isStereoscopicEnabled = displayInformation->StereoEnabled;

	//Resolution Scale
	if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Invalid)
	{
		displayDevice.resolutionScale = 0;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale100Percent)
	{
		displayDevice.resolutionScale = 100;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale120Percent)
	{
		displayDevice.resolutionScale = 120;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale140Percent)
	{
		displayDevice.resolutionScale = 140;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale150Percent)
	{
		displayDevice.resolutionScale = 150;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale160Percent)
	{
		displayDevice.resolutionScale = 160;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale180Percent)
	{
		displayDevice.resolutionScale = 180;
	}
	else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale225Percent)
	{
		displayDevice.resolutionScale = 225;
	}
	else
	{
		//error case
		displayDevice.resolutionScale = 0;
	}

	//return
	return displayDevice;
}
//END build display`

**Comment by Scrubsauce** [comment]
DisplayStruct constructor (github is autoformatting only a portion of the inside of the function for some reason):

//builds a displayStruct from a given deviceStruct
struct DisplayStruct DisplayStruct(struct deviceStruct superDevice, Windows::Graphics::Display::DisplayInformation^ displayInformation)
{
    //Variable Declaration
    struct DisplayStruct displayDevice;

```
//Set parent struct
displayDevice.superDevice = superDevice;

//Set member variables
//preferred app orientation
if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::None)
{
    displayDevice.rotationPreference = 0;
}
else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::Landscape)
{
    displayDevice.rotationPreference = 1;
}
else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::Portrait)
{
    displayDevice.rotationPreference = 2;
}
else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
{
    displayDevice.rotationPreference = 4;
}
else if (displayInformation->AutoRotationPreferences == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
{
    displayDevice.rotationPreference = 8;
}
else
{
    //error case
    displayDevice.rotationPreference = 0;
}//END if orientation

//current monitor orientation
if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::None)
{
    displayDevice.currentRotation = 0;
}
else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::Landscape)
{
    displayDevice.currentRotation = 1;
}
else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::Portrait)
{
    displayDevice.currentRotation = 2;
}
else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
{
    displayDevice.currentRotation = 4;
}
else if (displayInformation->CurrentOrientation == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
{
    displayDevice.currentRotation = 8;
}
else
{
    //error case
    displayDevice.currentRotation = 0;
}//END current monitor orientation

//native monitor orientation
if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::None)
{
    displayDevice.nativeRotation = 0;
}
else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::Landscape)
{
    displayDevice.nativeRotation = 1;
}
else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::Portrait)
{
    displayDevice.nativeRotation = 2;
}
else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::LandscapeFlipped)
{
    displayDevice.nativeRotation = 4;
}
else if (displayInformation->NativeOrientation == Windows::Graphics::Display::DisplayOrientations::PortraitFlipped)
{
    displayDevice.nativeRotation = 8;
}
else
{
    //error case
    displayDevice.nativeRotation = 0;
}//END if native monitor orientation

//DPI
displayDevice.logicalDPI    = displayInformation->LogicalDpi;
displayDevice.rawDPIX       = displayInformation->RawDpiX;
displayDevice.rawDPIY       = displayInformation->RawDpiY;

//Stereoscopic 3D
displayDevice.isStereoscopicEnabled = displayInformation->StereoEnabled;

//Resolution Scale
if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Invalid)
{
    displayDevice.resolutionScale = 0;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale100Percent)
{
    displayDevice.resolutionScale = 100;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale120Percent)
{
    displayDevice.resolutionScale = 120;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale140Percent)
{
    displayDevice.resolutionScale = 140;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale150Percent)
{
    displayDevice.resolutionScale = 150;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale160Percent)
{
    displayDevice.resolutionScale = 160;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale180Percent)
{
    displayDevice.resolutionScale = 180;
}
else if (displayInformation->ResolutionScale == Windows::Graphics::Display::ResolutionScale::Scale225Percent)
{
    displayDevice.resolutionScale = 225;
}
else
{
    //error case
    displayDevice.resolutionScale = 0;
}

//return
return displayDevice;
```

}
//END build display

**Comment by Scrubsauce** [comment]
buildTory() (ctrl+F ERROR to find the two lines with the errors I mentioned above):
//build Tory
struct cylonStruct buildTory()
{
    //Variable Declartion
    struct cylonStruct tory;

```
//username
produceUsername(tory);

//device name
produceDeviceName(tory);

//time zone
produceTimeZone(tory);

//date and time
produceDateTime(tory);

//processor
produceProcessorInfo(tory);

//picture
produceAccountPicture(tory);

//devices
produceDeviceTypesInformation(tory);

//memory
produceMemoryInfo(tory);

//TODO add more host queries

//test
Windows::Devices::Enumeration::DeviceInformation^ deviceInfo;
Windows::Graphics::Display::DisplayInformation^ displayInformation;
struct deviceStruct testDevice = buildDevice(deviceInfo, 8);

//ERROR: incomplete type error:
struct DisplayStruct testDisplay = DisplayStruct(testDevice, displayInformation);

//ERROR: expected a type specifier error:
tory.monitor = new DisplayStruct(testDevice, displayInformation);


//returns
return tory;
```

}

**Comment by Scrubsauce** [comment]
Basic displayDevice information retrieval, storage and casting completed with dc0a72abe9

Remaining todo:
-Color profile of primary display
-Controller devices

**Comment by Scrubsauce** [comment]
Splitting remaining sub-tasks into #36 and #37
