### ISSUE TITLE
Nightly Status Update 3/12

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#62]

**Comment by Simulacrum0** [comment]
1.) Hope its feeling more comfortable
2.) Congrats
3., 4., 5. ) Cool...will read this weekend
6.) Yeah, makes sense to specifically target Kit-Kat & Jellybean and pay attention to 'fallbacks' when an API/Service isn't availabe but the App will still run, detect their absence, and accommodate ( return a 'not applicable or minimal value, etc.' )
