### ISSUE TITLE
Set Jake up w/ Git Bash

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#9]
@Simulacrum0 
http://git-scm.com/downloads

**Comment by Simulacrum0** [comment]
All looks fine w/ Repo and pull down on my end.

**Comment by Simulacrum0** [comment]
( note: will check each morning around 5:30MST to allow for shorter or longer times in reply instead of end of day as i initially suggested ).

**Comment by Simulacrum0** [comment]
![akira__boomincity](https://cloud.githubusercontent.com/assets/8696781/6133029/f8b67768-b124-11e4-9ff3-c295b960a91c.jpg)
