### ISSUE TITLE
Refactor memory producer

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Foster#98]
See if UWP has a new method for retrieving memoryBytes field (and related fields added since Marrow)

**Comment by Scrubsauce** [comment]
@Simulacrum0 Memory API still locked for apps? Looks like you could put some Win32 stuff in your project and it will build properly, but they will reject your submission :( 
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bfe9d6f4-61bf-4ca2-bdef-69240cb92fdc/when-can-i-start-using-these-4-api-calls-eg-getproductinfo?forum=wpdevelop

**Comment by Scrubsauce** [comment]
https://msdn.microsoft.com/en-us/library/windows/apps/windows.system.memorymanager.aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-1

**Comment by Scrubsauce** [comment]
Completed as of 5df4fca

**Comment by Simulacrum0** [comment]
Acknowledged-
